apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: movie-ticket-app-route
  namespace: movie-app
  labels:
    app: movie-ticket-app
spec:
  to:
    kind: Service
    name: movie-ticket-app-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
